include ../vk.mk
srcs = \
	vkiceAlgo.C \
	vkiceAlgoPK.C \
	vkiceAlgoPKPGP.C \
	vkiceAlgoSymm.C \
	vkiceAlgoSymmBlowfish.C \
	vkiceAlgoSymmDES.C \
	vkiceAlgoSymmHydrogen.C \
	vkiceAlgoSymmTwoFish.C	\
	vkiceApp.C \
	ice.C
ice: ice.C
	g++  $(CPPFLAGS)  -o ice ice.C *.o ../vkmob/*.o ../vkapp/*.o
module: \
	vkiceAlgo.o \
	vkiceAlgoPK.o \
	vkiceAlgoPKPGP.o \
	vkiceAlgoSymm.o \
	vkiceAlgoSymmBlowfish.o \
	vkiceAlgoSymmDES.o \
	vkiceAlgoSymmHydrogen.o \
	vkiceAlgoSymmTwoFish.o \
	vkiceApp.o \
	ice
moduleClean:
	rm -f ice
moduleDepend:
moduleDependencies:
	cd ../vkapp && $(MAKE)
# DO NOT DELETE

vkiceAlgo.o: vkiceAlgo.h ../vkmob/vkmobJect.h ../vkDef.h
vkiceAlgo.o: /usr/include/assert.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkiceAlgo.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkiceAlgo.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/fstream
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/libio.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkiceAlgo.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkiceAlgo.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkiceAlgo.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkiceAlgo.o: /usr/include/stdarg.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/hash_map
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkiceAlgo.o: /usr/include/string.h /usr/include/limits.h
vkiceAlgo.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vkiceAlgo.o: /usr/include/sys/syslimits.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/new.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/new
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/exception
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/hash_set
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/iostream
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/list
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkiceAlgo.o: /usr/include/math.h /usr/include/gcc/darwin/default/g++/queue
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/slist
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/string
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/cstddef
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/cctype /usr/include/ctype.h
vkiceAlgo.o: /usr/include/runetype.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/cstring
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/iterator
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/cassert
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkiceAlgo.o: ../library/libstdc++/ducttape/sstream-2.95.3 /usr/include/time.h
vkiceAlgo.o: /usr/include/sys/time.h
vkiceAlgo.o: /usr/include/gcc/darwin/default/g++/vector
vkiceAlgoPK.o: vkiceAlgoPK.h vkiceAlgo.h ../vkmob/vkmobJect.h ../vkDef.h
vkiceAlgoPK.o: /usr/include/assert.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkiceAlgoPK.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkiceAlgoPK.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/fstream
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/libio.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkiceAlgoPK.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkiceAlgoPK.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkiceAlgoPK.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkiceAlgoPK.o: /usr/include/stdarg.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/hash_map
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkiceAlgoPK.o: /usr/include/string.h /usr/include/limits.h
vkiceAlgoPK.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vkiceAlgoPK.o: /usr/include/sys/syslimits.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/new.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/new
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/exception
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/hash_set
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/iostream
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/list
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkiceAlgoPK.o: /usr/include/math.h /usr/include/gcc/darwin/default/g++/queue
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/slist
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/string
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/cstddef
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/cctype
vkiceAlgoPK.o: /usr/include/ctype.h /usr/include/runetype.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/cstring
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/iterator
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/cassert
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkiceAlgoPK.o: ../library/libstdc++/ducttape/sstream-2.95.3
vkiceAlgoPK.o: /usr/include/time.h /usr/include/sys/time.h
vkiceAlgoPK.o: /usr/include/gcc/darwin/default/g++/vector
vkiceAlgoPKPGP.o: vkiceAlgoPKPGP.h vkiceAlgoPK.h vkiceAlgo.h
vkiceAlgoPKPGP.o: ../vkmob/vkmobJect.h ../vkDef.h /usr/include/assert.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkiceAlgoPKPGP.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkiceAlgoPKPGP.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/fstream
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/libio.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkiceAlgoPKPGP.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkiceAlgoPKPGP.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkiceAlgoPKPGP.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkiceAlgoPKPGP.o: /usr/include/stdarg.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/hash_map
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkiceAlgoPKPGP.o: /usr/include/string.h /usr/include/limits.h
vkiceAlgoPKPGP.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vkiceAlgoPKPGP.o: /usr/include/sys/syslimits.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/new.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/new
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/exception
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/hash_set
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/iostream
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/list
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkiceAlgoPKPGP.o: /usr/include/math.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/queue
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/slist
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/string
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/cstddef
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/cctype
vkiceAlgoPKPGP.o: /usr/include/ctype.h /usr/include/runetype.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/cstring
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/iterator
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/cassert
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkiceAlgoPKPGP.o: ../library/libstdc++/ducttape/sstream-2.95.3
vkiceAlgoPKPGP.o: /usr/include/time.h /usr/include/sys/time.h
vkiceAlgoPKPGP.o: /usr/include/gcc/darwin/default/g++/vector
vkiceAlgoSymm.o: vkiceAlgoSymm.h vkiceAlgo.h ../vkmob/vkmobJect.h ../vkDef.h
vkiceAlgoSymm.o: /usr/include/assert.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkiceAlgoSymm.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkiceAlgoSymm.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/fstream
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/libio.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkiceAlgoSymm.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkiceAlgoSymm.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkiceAlgoSymm.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkiceAlgoSymm.o: /usr/include/stdarg.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/hash_map
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkiceAlgoSymm.o: /usr/include/string.h /usr/include/limits.h
vkiceAlgoSymm.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vkiceAlgoSymm.o: /usr/include/sys/syslimits.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/new.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/new
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/exception
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/hash_set
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/iostream
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/list
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkiceAlgoSymm.o: /usr/include/math.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/queue
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/slist
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/string
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/cstddef
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/cctype
vkiceAlgoSymm.o: /usr/include/ctype.h /usr/include/runetype.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/cstring
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/iterator
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/cassert
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkiceAlgoSymm.o: ../library/libstdc++/ducttape/sstream-2.95.3
vkiceAlgoSymm.o: /usr/include/time.h /usr/include/sys/time.h
vkiceAlgoSymm.o: /usr/include/gcc/darwin/default/g++/vector
vkiceAlgoSymmBlowfish.o: vkiceAlgoSymmBlowfish.h vkiceAlgoSymm.h vkiceAlgo.h
vkiceAlgoSymmBlowfish.o: ../vkmob/vkmobJect.h ../vkDef.h
vkiceAlgoSymmBlowfish.o: /usr/include/assert.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkiceAlgoSymmBlowfish.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkiceAlgoSymmBlowfish.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/fstream
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/libio.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkiceAlgoSymmBlowfish.o: /usr/include/sys/types.h
vkiceAlgoSymmBlowfish.o: /usr/include/machine/types.h
vkiceAlgoSymmBlowfish.o: /usr/include/ppc/types.h
vkiceAlgoSymmBlowfish.o: /usr/include/machine/endian.h
vkiceAlgoSymmBlowfish.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkiceAlgoSymmBlowfish.o: /usr/include/stdarg.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/hash_map
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkiceAlgoSymmBlowfish.o: /usr/include/string.h /usr/include/limits.h
vkiceAlgoSymmBlowfish.o: /usr/include/machine/limits.h
vkiceAlgoSymmBlowfish.o: /usr/include/ppc/limits.h
vkiceAlgoSymmBlowfish.o: /usr/include/sys/syslimits.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/new.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/new
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/exception
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/hash_set
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/iostream
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/list
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkiceAlgoSymmBlowfish.o: /usr/include/math.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/queue
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/slist
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/string
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/cstddef
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/cctype
vkiceAlgoSymmBlowfish.o: /usr/include/ctype.h /usr/include/runetype.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/cstring
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/iterator
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/cassert
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkiceAlgoSymmBlowfish.o: ../library/libstdc++/ducttape/sstream-2.95.3
vkiceAlgoSymmBlowfish.o: /usr/include/time.h /usr/include/sys/time.h
vkiceAlgoSymmBlowfish.o: /usr/include/gcc/darwin/default/g++/vector
vkiceAlgoSymmDES.o: vkiceAlgoSymmDES.h vkiceAlgoSymm.h vkiceAlgo.h
vkiceAlgoSymmDES.o: ../vkmob/vkmobJect.h ../vkDef.h /usr/include/assert.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkiceAlgoSymmDES.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkiceAlgoSymmDES.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/fstream
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/libio.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkiceAlgoSymmDES.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkiceAlgoSymmDES.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkiceAlgoSymmDES.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkiceAlgoSymmDES.o: /usr/include/stdarg.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/hash_map
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkiceAlgoSymmDES.o: /usr/include/string.h /usr/include/limits.h
vkiceAlgoSymmDES.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vkiceAlgoSymmDES.o: /usr/include/sys/syslimits.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/new.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/new
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/exception
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/hash_set
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/iostream
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/list
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkiceAlgoSymmDES.o: /usr/include/math.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/queue
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/slist
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/string
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/cstddef
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/cctype
vkiceAlgoSymmDES.o: /usr/include/ctype.h /usr/include/runetype.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/cstring
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/iterator
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/cassert
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkiceAlgoSymmDES.o: ../library/libstdc++/ducttape/sstream-2.95.3
vkiceAlgoSymmDES.o: /usr/include/time.h /usr/include/sys/time.h
vkiceAlgoSymmDES.o: /usr/include/gcc/darwin/default/g++/vector
vkiceAlgoSymmHydrogen.o: vkiceAlgoSymmHydrogen.h vkiceAlgoSymm.h vkiceAlgo.h
vkiceAlgoSymmHydrogen.o: ../vkmob/vkmobJect.h ../vkDef.h
vkiceAlgoSymmHydrogen.o: /usr/include/assert.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkiceAlgoSymmHydrogen.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkiceAlgoSymmHydrogen.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/fstream
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/libio.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkiceAlgoSymmHydrogen.o: /usr/include/sys/types.h
vkiceAlgoSymmHydrogen.o: /usr/include/machine/types.h
vkiceAlgoSymmHydrogen.o: /usr/include/ppc/types.h
vkiceAlgoSymmHydrogen.o: /usr/include/machine/endian.h
vkiceAlgoSymmHydrogen.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkiceAlgoSymmHydrogen.o: /usr/include/stdarg.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/hash_map
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkiceAlgoSymmHydrogen.o: /usr/include/string.h /usr/include/limits.h
vkiceAlgoSymmHydrogen.o: /usr/include/machine/limits.h
vkiceAlgoSymmHydrogen.o: /usr/include/ppc/limits.h
vkiceAlgoSymmHydrogen.o: /usr/include/sys/syslimits.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/new.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/new
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/exception
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/hash_set
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/iostream
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/list
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkiceAlgoSymmHydrogen.o: /usr/include/math.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/queue
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/slist
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/string
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/cstddef
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/cctype
vkiceAlgoSymmHydrogen.o: /usr/include/ctype.h /usr/include/runetype.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/cstring
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/iterator
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/cassert
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkiceAlgoSymmHydrogen.o: ../library/libstdc++/ducttape/sstream-2.95.3
vkiceAlgoSymmHydrogen.o: /usr/include/time.h /usr/include/sys/time.h
vkiceAlgoSymmHydrogen.o: /usr/include/gcc/darwin/default/g++/vector
vkiceAlgoSymmTwoFish.o: vkiceAlgoSymmTwoFish.h vkiceAlgoSymm.h vkiceAlgo.h
vkiceAlgoSymmTwoFish.o: ../vkmob/vkmobJect.h ../vkDef.h /usr/include/assert.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkiceAlgoSymmTwoFish.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkiceAlgoSymmTwoFish.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/fstream
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/libio.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkiceAlgoSymmTwoFish.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkiceAlgoSymmTwoFish.o: /usr/include/ppc/types.h
vkiceAlgoSymmTwoFish.o: /usr/include/machine/endian.h
vkiceAlgoSymmTwoFish.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkiceAlgoSymmTwoFish.o: /usr/include/stdarg.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/hash_map
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkiceAlgoSymmTwoFish.o: /usr/include/string.h /usr/include/limits.h
vkiceAlgoSymmTwoFish.o: /usr/include/machine/limits.h
vkiceAlgoSymmTwoFish.o: /usr/include/ppc/limits.h
vkiceAlgoSymmTwoFish.o: /usr/include/sys/syslimits.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/new.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/new
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/exception
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/hash_set
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/iostream
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/list
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkiceAlgoSymmTwoFish.o: /usr/include/math.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/queue
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/slist
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/string
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/cstddef
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/cctype
vkiceAlgoSymmTwoFish.o: /usr/include/ctype.h /usr/include/runetype.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/cstring
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/iterator
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/cassert
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkiceAlgoSymmTwoFish.o: ../library/libstdc++/ducttape/sstream-2.95.3
vkiceAlgoSymmTwoFish.o: /usr/include/time.h /usr/include/sys/time.h
vkiceAlgoSymmTwoFish.o: /usr/include/gcc/darwin/default/g++/vector
vkiceApp.o: vkiceApp.h ../vkapp/vkappShell.h ../vkapp/vkappApp.h
vkiceApp.o: ../vkmob/vkmobFuncEqString.h ../vkmob/vkmobJect.h ../vkDef.h
vkiceApp.o: /usr/include/assert.h /usr/include/gcc/darwin/default/g++/cstdlib
vkiceApp.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkiceApp.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/fstream
vkiceApp.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/libio.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkiceApp.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkiceApp.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkiceApp.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkiceApp.o: /usr/include/stdarg.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/hash_map
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkiceApp.o: /usr/include/string.h /usr/include/limits.h
vkiceApp.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vkiceApp.o: /usr/include/sys/syslimits.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/new.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/new
vkiceApp.o: /usr/include/gcc/darwin/default/g++/exception
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/hash_set
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/iostream
vkiceApp.o: /usr/include/gcc/darwin/default/g++/list
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkiceApp.o: /usr/include/math.h /usr/include/gcc/darwin/default/g++/queue
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/slist
vkiceApp.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/string
vkiceApp.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/cstddef
vkiceApp.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/cctype /usr/include/ctype.h
vkiceApp.o: /usr/include/runetype.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/cstring
vkiceApp.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/iterator
vkiceApp.o: /usr/include/gcc/darwin/default/g++/cassert
vkiceApp.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkiceApp.o: ../library/libstdc++/ducttape/sstream-2.95.3 /usr/include/time.h
vkiceApp.o: /usr/include/sys/time.h
vkiceApp.o: /usr/include/gcc/darwin/default/g++/vector
vkiceApp.o: ../vkmob/vkmobFuncHashString.h ../vkmob/vkmobJect.h
vkiceApp.o: vkiceAlgoSymmHydrogen.h vkiceAlgoSymm.h vkiceAlgo.h
ice.o: vkiceApp.h ../vkapp/vkappShell.h ../vkapp/vkappApp.h
ice.o: ../vkmob/vkmobFuncEqString.h ../vkmob/vkmobJect.h ../vkDef.h
ice.o: /usr/include/assert.h /usr/include/gcc/darwin/default/g++/cstdlib
ice.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
ice.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
ice.o: /usr/include/gcc/darwin/default/g++/fstream
ice.o: /usr/include/gcc/darwin/default/g++/fstream.h
ice.o: /usr/include/gcc/darwin/default/g++/iostream.h
ice.o: /usr/include/gcc/darwin/default/g++/streambuf.h
ice.o: /usr/include/gcc/darwin/default/g++/libio.h
ice.o: /usr/include/gcc/darwin/default/g++/_G_config.h
ice.o: /usr/include/sys/types.h /usr/include/machine/types.h
ice.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
ice.o: /usr/include/ppc/endian.h /usr/include/stddef.h /usr/include/stdarg.h
ice.o: /usr/include/gcc/darwin/default/g++/hash_map
ice.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
ice.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
ice.o: /usr/include/gcc/darwin/default/g++/stl_config.h
ice.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
ice.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
ice.o: /usr/include/gcc/darwin/default/g++/type_traits.h
ice.o: /usr/include/string.h /usr/include/limits.h
ice.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
ice.o: /usr/include/sys/syslimits.h /usr/include/gcc/darwin/default/g++/new.h
ice.o: /usr/include/gcc/darwin/default/g++/new
ice.o: /usr/include/gcc/darwin/default/g++/exception
ice.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
ice.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
ice.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
ice.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
ice.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
ice.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
ice.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
ice.o: /usr/include/gcc/darwin/default/g++/stl_function.h
ice.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
ice.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
ice.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
ice.o: /usr/include/gcc/darwin/default/g++/hash_set
ice.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
ice.o: /usr/include/gcc/darwin/default/g++/iostream
ice.o: /usr/include/gcc/darwin/default/g++/list
ice.o: /usr/include/gcc/darwin/default/g++/stl_list.h /usr/include/math.h
ice.o: /usr/include/gcc/darwin/default/g++/queue
ice.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
ice.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
ice.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
ice.o: /usr/include/gcc/darwin/default/g++/slist
ice.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
ice.o: /usr/include/gcc/darwin/default/g++/string
ice.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
ice.o: /usr/include/gcc/darwin/default/g++/cstddef
ice.o: /usr/include/gcc/darwin/default/g++/std/straits.h
ice.o: /usr/include/gcc/darwin/default/g++/cctype /usr/include/ctype.h
ice.o: /usr/include/runetype.h /usr/include/gcc/darwin/default/g++/cstring
ice.o: /usr/include/gcc/darwin/default/g++/alloc.h
ice.o: /usr/include/gcc/darwin/default/g++/iterator
ice.o: /usr/include/gcc/darwin/default/g++/cassert
ice.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
ice.o: ../library/libstdc++/ducttape/sstream-2.95.3 /usr/include/time.h
ice.o: /usr/include/sys/time.h /usr/include/gcc/darwin/default/g++/vector
ice.o: ../vkmob/vkmobFuncHashString.h ../vkmob/vkmobJect.h
