include ../vk.mk
srcs = \
	vklizBrain.C \
	vklizEye.C \
	vklizMon.C \
	vklizMonShell.C \
	vklizMonWeb.C \
	test_brain.C \
	test_eye.C
module: \
	vklizBrain.o \
	vklizEye.o \
	vklizMon.o \
	vklizMonShell.o \
	vklizMonWeb.o \
	test_brain \
	test_eye
moduleClean:
	rm -f test_brain
	rm -f test_eye
moduleDepend:
moduleDependencies:
	cd ../vkmob && $(MAKE)
test_brain: $(srcs)
	g++  $(CPPFLAGS)  -o test_brain test_brain.C *.o ../vkmob/*.o
test_eye: $(srcs)
	g++  $(CPPFLAGS)  -o test_eye test_eye.C *.o ../vkmob/*.o
# DO NOT DELETE

vklizBrain.o: vklizBrain.h ../vkmob/vkmobJect.h ../vkDef.h
vklizBrain.o: /usr/include/assert.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/cstdlib
vklizBrain.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vklizBrain.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/fstream
vklizBrain.o: /usr/include/gcc/darwin/default/g++/fstream.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/iostream.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/libio.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vklizBrain.o: /usr/include/sys/types.h /usr/include/machine/types.h
vklizBrain.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vklizBrain.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vklizBrain.o: /usr/include/stdarg.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/hash_map
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vklizBrain.o: /usr/include/string.h /usr/include/limits.h
vklizBrain.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vklizBrain.o: /usr/include/sys/syslimits.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/new.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/new
vklizBrain.o: /usr/include/gcc/darwin/default/g++/exception
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/hash_set
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/iostream
vklizBrain.o: /usr/include/gcc/darwin/default/g++/list
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vklizBrain.o: /usr/include/math.h /usr/include/gcc/darwin/default/g++/queue
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/slist
vklizBrain.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/string
vklizBrain.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/cstddef
vklizBrain.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/cctype /usr/include/ctype.h
vklizBrain.o: /usr/include/runetype.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/cstring
vklizBrain.o: /usr/include/gcc/darwin/default/g++/alloc.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/iterator
vklizBrain.o: /usr/include/gcc/darwin/default/g++/cassert
vklizBrain.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vklizBrain.o: ../library/libstdc++/ducttape/sstream-2.95.3
vklizBrain.o: /usr/include/time.h /usr/include/sys/time.h
vklizBrain.o: /usr/include/gcc/darwin/default/g++/vector
vklizEye.o: vklizEye.h ../vkmob/vkmobJect.h ../vkDef.h /usr/include/assert.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/cstdlib /usr/include/stdlib.h
vklizEye.o: /usr/include/machine/ansi.h /usr/include/ppc/ansi.h
vklizEye.o: /usr/include/sys/cdefs.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/fstream
vklizEye.o: /usr/include/gcc/darwin/default/g++/fstream.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/iostream.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/libio.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vklizEye.o: /usr/include/sys/types.h /usr/include/machine/types.h
vklizEye.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vklizEye.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vklizEye.o: /usr/include/stdarg.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/hash_map
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vklizEye.o: /usr/include/string.h /usr/include/limits.h
vklizEye.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vklizEye.o: /usr/include/sys/syslimits.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/new.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/new
vklizEye.o: /usr/include/gcc/darwin/default/g++/exception
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/hash_set
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/iostream
vklizEye.o: /usr/include/gcc/darwin/default/g++/list
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vklizEye.o: /usr/include/math.h /usr/include/gcc/darwin/default/g++/queue
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/slist
vklizEye.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/string
vklizEye.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/cstddef
vklizEye.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/cctype /usr/include/ctype.h
vklizEye.o: /usr/include/runetype.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/cstring
vklizEye.o: /usr/include/gcc/darwin/default/g++/alloc.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/iterator
vklizEye.o: /usr/include/gcc/darwin/default/g++/cassert
vklizEye.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vklizEye.o: ../library/libstdc++/ducttape/sstream-2.95.3 /usr/include/time.h
vklizEye.o: /usr/include/sys/time.h
vklizEye.o: /usr/include/gcc/darwin/default/g++/vector
vklizMon.o: vklizMon.h
vklizMonShell.o: vklizMonShell.h
vklizMonWeb.o: vklizMonWeb.h
test_brain.o: vklizBrain.h ../vkmob/vkmobJect.h ../vkDef.h
test_brain.o: /usr/include/assert.h
test_brain.o: /usr/include/gcc/darwin/default/g++/cstdlib
test_brain.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
test_brain.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
test_brain.o: /usr/include/gcc/darwin/default/g++/fstream
test_brain.o: /usr/include/gcc/darwin/default/g++/fstream.h
test_brain.o: /usr/include/gcc/darwin/default/g++/iostream.h
test_brain.o: /usr/include/gcc/darwin/default/g++/streambuf.h
test_brain.o: /usr/include/gcc/darwin/default/g++/libio.h
test_brain.o: /usr/include/gcc/darwin/default/g++/_G_config.h
test_brain.o: /usr/include/sys/types.h /usr/include/machine/types.h
test_brain.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
test_brain.o: /usr/include/ppc/endian.h /usr/include/stddef.h
test_brain.o: /usr/include/stdarg.h
test_brain.o: /usr/include/gcc/darwin/default/g++/hash_map
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_config.h
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
test_brain.o: /usr/include/gcc/darwin/default/g++/type_traits.h
test_brain.o: /usr/include/string.h /usr/include/limits.h
test_brain.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
test_brain.o: /usr/include/sys/syslimits.h
test_brain.o: /usr/include/gcc/darwin/default/g++/new.h
test_brain.o: /usr/include/gcc/darwin/default/g++/new
test_brain.o: /usr/include/gcc/darwin/default/g++/exception
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_function.h
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
test_brain.o: /usr/include/gcc/darwin/default/g++/hash_set
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
test_brain.o: /usr/include/gcc/darwin/default/g++/iostream
test_brain.o: /usr/include/gcc/darwin/default/g++/list
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_list.h
test_brain.o: /usr/include/math.h /usr/include/gcc/darwin/default/g++/queue
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
test_brain.o: /usr/include/gcc/darwin/default/g++/slist
test_brain.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
test_brain.o: /usr/include/gcc/darwin/default/g++/string
test_brain.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
test_brain.o: /usr/include/gcc/darwin/default/g++/cstddef
test_brain.o: /usr/include/gcc/darwin/default/g++/std/straits.h
test_brain.o: /usr/include/gcc/darwin/default/g++/cctype /usr/include/ctype.h
test_brain.o: /usr/include/runetype.h
test_brain.o: /usr/include/gcc/darwin/default/g++/cstring
test_brain.o: /usr/include/gcc/darwin/default/g++/alloc.h
test_brain.o: /usr/include/gcc/darwin/default/g++/iterator
test_brain.o: /usr/include/gcc/darwin/default/g++/cassert
test_brain.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
test_brain.o: ../library/libstdc++/ducttape/sstream-2.95.3
test_brain.o: /usr/include/time.h /usr/include/sys/time.h
test_brain.o: /usr/include/gcc/darwin/default/g++/vector
test_eye.o: vklizEye.h ../vkmob/vkmobJect.h ../vkDef.h /usr/include/assert.h
test_eye.o: /usr/include/gcc/darwin/default/g++/cstdlib /usr/include/stdlib.h
test_eye.o: /usr/include/machine/ansi.h /usr/include/ppc/ansi.h
test_eye.o: /usr/include/sys/cdefs.h
test_eye.o: /usr/include/gcc/darwin/default/g++/fstream
test_eye.o: /usr/include/gcc/darwin/default/g++/fstream.h
test_eye.o: /usr/include/gcc/darwin/default/g++/iostream.h
test_eye.o: /usr/include/gcc/darwin/default/g++/streambuf.h
test_eye.o: /usr/include/gcc/darwin/default/g++/libio.h
test_eye.o: /usr/include/gcc/darwin/default/g++/_G_config.h
test_eye.o: /usr/include/sys/types.h /usr/include/machine/types.h
test_eye.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
test_eye.o: /usr/include/ppc/endian.h /usr/include/stddef.h
test_eye.o: /usr/include/stdarg.h
test_eye.o: /usr/include/gcc/darwin/default/g++/hash_map
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_config.h
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
test_eye.o: /usr/include/gcc/darwin/default/g++/type_traits.h
test_eye.o: /usr/include/string.h /usr/include/limits.h
test_eye.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
test_eye.o: /usr/include/sys/syslimits.h
test_eye.o: /usr/include/gcc/darwin/default/g++/new.h
test_eye.o: /usr/include/gcc/darwin/default/g++/new
test_eye.o: /usr/include/gcc/darwin/default/g++/exception
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_function.h
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
test_eye.o: /usr/include/gcc/darwin/default/g++/hash_set
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
test_eye.o: /usr/include/gcc/darwin/default/g++/iostream
test_eye.o: /usr/include/gcc/darwin/default/g++/list
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_list.h
test_eye.o: /usr/include/math.h /usr/include/gcc/darwin/default/g++/queue
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
test_eye.o: /usr/include/gcc/darwin/default/g++/slist
test_eye.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
test_eye.o: /usr/include/gcc/darwin/default/g++/string
test_eye.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
test_eye.o: /usr/include/gcc/darwin/default/g++/cstddef
test_eye.o: /usr/include/gcc/darwin/default/g++/std/straits.h
test_eye.o: /usr/include/gcc/darwin/default/g++/cctype /usr/include/ctype.h
test_eye.o: /usr/include/runetype.h
test_eye.o: /usr/include/gcc/darwin/default/g++/cstring
test_eye.o: /usr/include/gcc/darwin/default/g++/alloc.h
test_eye.o: /usr/include/gcc/darwin/default/g++/iterator
test_eye.o: /usr/include/gcc/darwin/default/g++/cassert
test_eye.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
test_eye.o: ../library/libstdc++/ducttape/sstream-2.95.3 /usr/include/time.h
test_eye.o: /usr/include/sys/time.h
test_eye.o: /usr/include/gcc/darwin/default/g++/vector
