include ../vk.mk
srcs = \
	vkshShell.C
module: \
	vkshShell.o
moduleClean:
moduleDepend:
moduleDependencies:
	cd ../vkmob && $(MAKE)
# DO NOT DELETE

vkshShell.o: vkshShell.h ../vkmob/vkmobJect.h ../vkDef.h
vkshShell.o: /usr/include/assert.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkshShell.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkshShell.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/fstream
vkshShell.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/libio.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkshShell.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkshShell.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkshShell.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkshShell.o: /usr/include/stdarg.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/hash_map
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkshShell.o: /usr/include/string.h /usr/include/limits.h
vkshShell.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vkshShell.o: /usr/include/sys/syslimits.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/new.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/new
vkshShell.o: /usr/include/gcc/darwin/default/g++/exception
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/hash_set
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/iostream
vkshShell.o: /usr/include/gcc/darwin/default/g++/list
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkshShell.o: /usr/include/math.h /usr/include/gcc/darwin/default/g++/queue
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/slist
vkshShell.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/string
vkshShell.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/cstddef
vkshShell.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/cctype /usr/include/ctype.h
vkshShell.o: /usr/include/runetype.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/cstring
vkshShell.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/iterator
vkshShell.o: /usr/include/gcc/darwin/default/g++/cassert
vkshShell.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkshShell.o: ../library/libstdc++/ducttape/sstream-2.95.3 /usr/include/time.h
vkshShell.o: /usr/include/sys/time.h
vkshShell.o: /usr/include/gcc/darwin/default/g++/vector
