include ../vk.mk
srcs = \
	vkpheHyperStream.C \
	vkpheHyperToken.C \
	vkpheIndiv.C \
	vkpheIndivDelimit.C \
	vkpheIndivEncapsulate.C \
	vkpheIndivFixWidth.C \
	vkpheSensor.C \
	test_vkpheHyperToken.C
module: \
	vkpheHyperStream.o \
	vkpheHyperToken.o \
	vkpheIndiv.o \
	vkpheIndivDelimit.o \
	vkpheIndivEncapsulate.o \
	vkpheIndivFixWidth.o \
	vkpheSensor.o \
	test_vkpheHyperToken
moduleClean:
	rm -f test_vkpheHyperToken
moduleDepend:
moduleDependencies:
	cd ../vkmob && $(MAKE)
test_vkpheHyperToken: $(srcs)
	g++  $(CPPFLAGS)  -o test_vkpheHyperToken test_vkpheHyperToken.C *.o ../vkmob/*.o
# DO NOT DELETE

vkpheHyperStream.o: vkpheHyperStream.h ../vkmob/vkmobJect.h ../vkDef.h
vkpheHyperStream.o: /usr/include/assert.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkpheHyperStream.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkpheHyperStream.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/fstream
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/libio.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkpheHyperStream.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkpheHyperStream.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkpheHyperStream.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkpheHyperStream.o: /usr/include/stdarg.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/hash_map
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkpheHyperStream.o: /usr/include/string.h /usr/include/limits.h
vkpheHyperStream.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vkpheHyperStream.o: /usr/include/sys/syslimits.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/new.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/new
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/exception
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/hash_set
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/iostream
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/list
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkpheHyperStream.o: /usr/include/math.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/queue
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/slist
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/string
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/cstddef
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/cctype
vkpheHyperStream.o: /usr/include/ctype.h /usr/include/runetype.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/cstring
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/iterator
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/cassert
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkpheHyperStream.o: ../library/libstdc++/ducttape/sstream-2.95.3
vkpheHyperStream.o: /usr/include/time.h /usr/include/sys/time.h
vkpheHyperStream.o: /usr/include/gcc/darwin/default/g++/vector
vkpheHyperStream.o: vkpheHyperToken.h
vkpheHyperToken.o: vkpheHyperToken.h ../vkmob/vkmobJect.h ../vkDef.h
vkpheHyperToken.o: /usr/include/assert.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkpheHyperToken.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkpheHyperToken.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/fstream
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/libio.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkpheHyperToken.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkpheHyperToken.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkpheHyperToken.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkpheHyperToken.o: /usr/include/stdarg.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/hash_map
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkpheHyperToken.o: /usr/include/string.h /usr/include/limits.h
vkpheHyperToken.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vkpheHyperToken.o: /usr/include/sys/syslimits.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/new.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/new
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/exception
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/hash_set
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/iostream
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/list
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkpheHyperToken.o: /usr/include/math.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/queue
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/slist
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/string
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/cstddef
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/cctype
vkpheHyperToken.o: /usr/include/ctype.h /usr/include/runetype.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/cstring
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/iterator
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/cassert
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkpheHyperToken.o: ../library/libstdc++/ducttape/sstream-2.95.3
vkpheHyperToken.o: /usr/include/time.h /usr/include/sys/time.h
vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/vector
vkpheIndiv.o: vkpheIndiv.h ../vkmob/vkmobJect.h ../vkDef.h
vkpheIndiv.o: /usr/include/assert.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkpheIndiv.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkpheIndiv.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/fstream
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/libio.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkpheIndiv.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkpheIndiv.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkpheIndiv.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkpheIndiv.o: /usr/include/stdarg.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/hash_map
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkpheIndiv.o: /usr/include/string.h /usr/include/limits.h
vkpheIndiv.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vkpheIndiv.o: /usr/include/sys/syslimits.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/new.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/new
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/exception
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/hash_set
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/iostream
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/list
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkpheIndiv.o: /usr/include/math.h /usr/include/gcc/darwin/default/g++/queue
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/slist
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/string
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/cstddef
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/cctype /usr/include/ctype.h
vkpheIndiv.o: /usr/include/runetype.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/cstring
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/iterator
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/cassert
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkpheIndiv.o: ../library/libstdc++/ducttape/sstream-2.95.3
vkpheIndiv.o: /usr/include/time.h /usr/include/sys/time.h
vkpheIndiv.o: /usr/include/gcc/darwin/default/g++/vector
vkpheIndivDelimit.o: vkpheIndivDelimit.h vkpheIndiv.h ../vkmob/vkmobJect.h
vkpheIndivDelimit.o: ../vkDef.h /usr/include/assert.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkpheIndivDelimit.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkpheIndivDelimit.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/fstream
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/libio.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkpheIndivDelimit.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkpheIndivDelimit.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkpheIndivDelimit.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkpheIndivDelimit.o: /usr/include/stdarg.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/hash_map
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkpheIndivDelimit.o: /usr/include/string.h /usr/include/limits.h
vkpheIndivDelimit.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vkpheIndivDelimit.o: /usr/include/sys/syslimits.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/new.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/new
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/exception
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/hash_set
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/iostream
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/list
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkpheIndivDelimit.o: /usr/include/math.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/queue
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/slist
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/string
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/cstddef
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/cctype
vkpheIndivDelimit.o: /usr/include/ctype.h /usr/include/runetype.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/cstring
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/iterator
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/cassert
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkpheIndivDelimit.o: ../library/libstdc++/ducttape/sstream-2.95.3
vkpheIndivDelimit.o: /usr/include/time.h /usr/include/sys/time.h
vkpheIndivDelimit.o: /usr/include/gcc/darwin/default/g++/vector
vkpheIndivEncapsulate.o: vkpheIndivEncapsulate.h vkpheIndiv.h
vkpheIndivEncapsulate.o: ../vkmob/vkmobJect.h ../vkDef.h
vkpheIndivEncapsulate.o: /usr/include/assert.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkpheIndivEncapsulate.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkpheIndivEncapsulate.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/fstream
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/libio.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkpheIndivEncapsulate.o: /usr/include/sys/types.h
vkpheIndivEncapsulate.o: /usr/include/machine/types.h
vkpheIndivEncapsulate.o: /usr/include/ppc/types.h
vkpheIndivEncapsulate.o: /usr/include/machine/endian.h
vkpheIndivEncapsulate.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkpheIndivEncapsulate.o: /usr/include/stdarg.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/hash_map
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkpheIndivEncapsulate.o: /usr/include/string.h /usr/include/limits.h
vkpheIndivEncapsulate.o: /usr/include/machine/limits.h
vkpheIndivEncapsulate.o: /usr/include/ppc/limits.h
vkpheIndivEncapsulate.o: /usr/include/sys/syslimits.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/new.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/new
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/exception
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/hash_set
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/iostream
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/list
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkpheIndivEncapsulate.o: /usr/include/math.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/queue
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/slist
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/string
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/cstddef
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/cctype
vkpheIndivEncapsulate.o: /usr/include/ctype.h /usr/include/runetype.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/cstring
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/iterator
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/cassert
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkpheIndivEncapsulate.o: ../library/libstdc++/ducttape/sstream-2.95.3
vkpheIndivEncapsulate.o: /usr/include/time.h /usr/include/sys/time.h
vkpheIndivEncapsulate.o: /usr/include/gcc/darwin/default/g++/vector
vkpheIndivFixWidth.o: vkpheIndivFixWidth.h vkpheIndiv.h ../vkmob/vkmobJect.h
vkpheIndivFixWidth.o: ../vkDef.h /usr/include/assert.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkpheIndivFixWidth.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkpheIndivFixWidth.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/fstream
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/libio.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkpheIndivFixWidth.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkpheIndivFixWidth.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkpheIndivFixWidth.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkpheIndivFixWidth.o: /usr/include/stdarg.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/hash_map
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkpheIndivFixWidth.o: /usr/include/string.h /usr/include/limits.h
vkpheIndivFixWidth.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vkpheIndivFixWidth.o: /usr/include/sys/syslimits.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/new.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/new
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/exception
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/hash_set
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/iostream
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/list
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkpheIndivFixWidth.o: /usr/include/math.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/queue
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/slist
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/string
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/cstddef
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/cctype
vkpheIndivFixWidth.o: /usr/include/ctype.h /usr/include/runetype.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/cstring
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/iterator
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/cassert
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkpheIndivFixWidth.o: ../library/libstdc++/ducttape/sstream-2.95.3
vkpheIndivFixWidth.o: /usr/include/time.h /usr/include/sys/time.h
vkpheIndivFixWidth.o: /usr/include/gcc/darwin/default/g++/vector
vkpheSensor.o: vkpheSensor.h ../vkmob/vkmobJect.h ../vkDef.h
vkpheSensor.o: /usr/include/assert.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkpheSensor.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkpheSensor.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/fstream
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/libio.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkpheSensor.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkpheSensor.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkpheSensor.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkpheSensor.o: /usr/include/stdarg.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/hash_map
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkpheSensor.o: /usr/include/string.h /usr/include/limits.h
vkpheSensor.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vkpheSensor.o: /usr/include/sys/syslimits.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/new.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/new
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/exception
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/hash_set
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/iostream
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/list
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkpheSensor.o: /usr/include/math.h /usr/include/gcc/darwin/default/g++/queue
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/slist
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/string
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/cstddef
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/cctype
vkpheSensor.o: /usr/include/ctype.h /usr/include/runetype.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/cstring
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/iterator
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/cassert
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkpheSensor.o: ../library/libstdc++/ducttape/sstream-2.95.3
vkpheSensor.o: /usr/include/time.h /usr/include/sys/time.h
vkpheSensor.o: /usr/include/gcc/darwin/default/g++/vector vkpheIndiv.h
test_vkpheHyperToken.o: vkpheHyperToken.h ../vkmob/vkmobJect.h ../vkDef.h
test_vkpheHyperToken.o: /usr/include/assert.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/cstdlib
test_vkpheHyperToken.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
test_vkpheHyperToken.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/fstream
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/fstream.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/iostream.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/streambuf.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/libio.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/_G_config.h
test_vkpheHyperToken.o: /usr/include/sys/types.h /usr/include/machine/types.h
test_vkpheHyperToken.o: /usr/include/ppc/types.h
test_vkpheHyperToken.o: /usr/include/machine/endian.h
test_vkpheHyperToken.o: /usr/include/ppc/endian.h /usr/include/stddef.h
test_vkpheHyperToken.o: /usr/include/stdarg.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/hash_map
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_config.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/type_traits.h
test_vkpheHyperToken.o: /usr/include/string.h /usr/include/limits.h
test_vkpheHyperToken.o: /usr/include/machine/limits.h
test_vkpheHyperToken.o: /usr/include/ppc/limits.h
test_vkpheHyperToken.o: /usr/include/sys/syslimits.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/new.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/new
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/exception
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_function.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/hash_set
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/iostream
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/list
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_list.h
test_vkpheHyperToken.o: /usr/include/math.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/queue
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/slist
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/string
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/cstddef
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/std/straits.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/cctype
test_vkpheHyperToken.o: /usr/include/ctype.h /usr/include/runetype.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/cstring
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/alloc.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/iterator
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/cassert
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
test_vkpheHyperToken.o: ../library/libstdc++/ducttape/sstream-2.95.3
test_vkpheHyperToken.o: /usr/include/time.h /usr/include/sys/time.h
test_vkpheHyperToken.o: /usr/include/gcc/darwin/default/g++/vector
