include ../vk.mk
srcs = \
	vkwwwApp.C \
	index.C
index: $(srcs)
	g++  $(CPPFLAGS)  -o index.cgi index.C *.o ../vkapp/*.o ../vkcgi/*.o ../vkhtml/*.o ../vkmob/*.o
module: \
	vkwwwApp.o \
	index
moduleClean:
	rm -f index.cgi
moduleDepend:
moduleDependencies:
	cd ../vkcgi && $(MAKE)
# DO NOT DELETE

vkwwwApp.o: vkwwwApp.h ../vkcgi/vkcgiApp.h ../vkcgi/vkcgiMIMEType.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/string
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/cstddef /usr/include/stddef.h
vkwwwApp.o: /usr/include/machine/ansi.h /usr/include/ppc/ansi.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/cctype /usr/include/ctype.h
vkwwwApp.o: /usr/include/runetype.h /usr/include/sys/cdefs.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/cstring /usr/include/string.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkwwwApp.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkwwwApp.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkwwwApp.o: /usr/include/ppc/endian.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/libio.h /usr/include/stdarg.h
vkwwwApp.o: /usr/include/stdlib.h /usr/include/assert.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/iterator
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/cassert
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkwwwApp.o: ../vkapp/vkappApp.h ../vkmob/vkmobFuncEqString.h
vkwwwApp.o: ../vkmob/vkmobJect.h ../vkDef.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/fstream
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/hash_map
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkwwwApp.o: /usr/include/limits.h /usr/include/machine/limits.h
vkwwwApp.o: /usr/include/ppc/limits.h /usr/include/sys/syslimits.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/new.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/new
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/exception
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/hash_set
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/iostream
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/list
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkwwwApp.o: /usr/include/math.h /usr/include/gcc/darwin/default/g++/queue
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/slist
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkwwwApp.o: ../library/libstdc++/ducttape/sstream-2.95.3 /usr/include/time.h
vkwwwApp.o: /usr/include/sys/time.h
vkwwwApp.o: /usr/include/gcc/darwin/default/g++/vector
vkwwwApp.o: ../vkmob/vkmobFuncHashString.h ../vkmob/vkmobJect.h
index.o: vkwwwApp.h ../vkcgi/vkcgiApp.h ../vkcgi/vkcgiMIMEType.h
index.o: /usr/include/gcc/darwin/default/g++/string
index.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
index.o: /usr/include/gcc/darwin/default/g++/cstddef /usr/include/stddef.h
index.o: /usr/include/machine/ansi.h /usr/include/ppc/ansi.h
index.o: /usr/include/gcc/darwin/default/g++/std/straits.h
index.o: /usr/include/gcc/darwin/default/g++/cctype /usr/include/ctype.h
index.o: /usr/include/runetype.h /usr/include/sys/cdefs.h
index.o: /usr/include/gcc/darwin/default/g++/cstring /usr/include/string.h
index.o: /usr/include/gcc/darwin/default/g++/alloc.h
index.o: /usr/include/gcc/darwin/default/g++/stl_config.h
index.o: /usr/include/gcc/darwin/default/g++/_G_config.h
index.o: /usr/include/sys/types.h /usr/include/machine/types.h
index.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
index.o: /usr/include/ppc/endian.h
index.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
index.o: /usr/include/gcc/darwin/default/g++/iostream.h
index.o: /usr/include/gcc/darwin/default/g++/streambuf.h
index.o: /usr/include/gcc/darwin/default/g++/libio.h /usr/include/stdarg.h
index.o: /usr/include/stdlib.h /usr/include/assert.h
index.o: /usr/include/gcc/darwin/default/g++/iterator
index.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
index.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
index.o: /usr/include/gcc/darwin/default/g++/cassert
index.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
index.o: ../vkapp/vkappApp.h ../vkmob/vkmobFuncEqString.h
index.o: ../vkmob/vkmobJect.h ../vkDef.h
index.o: /usr/include/gcc/darwin/default/g++/cstdlib
index.o: /usr/include/gcc/darwin/default/g++/fstream
index.o: /usr/include/gcc/darwin/default/g++/fstream.h
index.o: /usr/include/gcc/darwin/default/g++/hash_map
index.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
index.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
index.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
index.o: /usr/include/gcc/darwin/default/g++/type_traits.h
index.o: /usr/include/limits.h /usr/include/machine/limits.h
index.o: /usr/include/ppc/limits.h /usr/include/sys/syslimits.h
index.o: /usr/include/gcc/darwin/default/g++/new.h
index.o: /usr/include/gcc/darwin/default/g++/new
index.o: /usr/include/gcc/darwin/default/g++/exception
index.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
index.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
index.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
index.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
index.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
index.o: /usr/include/gcc/darwin/default/g++/stl_function.h
index.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
index.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
index.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
index.o: /usr/include/gcc/darwin/default/g++/hash_set
index.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
index.o: /usr/include/gcc/darwin/default/g++/iostream
index.o: /usr/include/gcc/darwin/default/g++/list
index.o: /usr/include/gcc/darwin/default/g++/stl_list.h /usr/include/math.h
index.o: /usr/include/gcc/darwin/default/g++/queue
index.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
index.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
index.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
index.o: /usr/include/gcc/darwin/default/g++/slist
index.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
index.o: ../library/libstdc++/ducttape/sstream-2.95.3 /usr/include/time.h
index.o: /usr/include/sys/time.h /usr/include/gcc/darwin/default/g++/vector
index.o: ../vkmob/vkmobFuncHashString.h ../vkmob/vkmobJect.h
