include ../vk.mk
srcs = \
	vkbullMarket.C \
	vkbullSecurity.C \
	test_vkbull.C
module: \
	vkbullMarket.o \
	vkbullSecurity.o \
	test_vkbull
moduleClean:
	rm -f test_vkbull
moduleDepend:
moduleDependencies:
	cd ../vkmob && $(MAKE)
test_vkbull: $(srcs)
	g++  $(CPPFLAGS)  -o test_vkbull test_vkbull.C *.o ../vkmob/*.o
# DO NOT DELETE

vkbullMarket.o: vkbullMarket.h ../vkmob/vkmobJect.h ../vkDef.h
vkbullMarket.o: /usr/include/assert.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkbullMarket.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkbullMarket.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/fstream
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/libio.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkbullMarket.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkbullMarket.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkbullMarket.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkbullMarket.o: /usr/include/stdarg.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/hash_map
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkbullMarket.o: /usr/include/string.h /usr/include/limits.h
vkbullMarket.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vkbullMarket.o: /usr/include/sys/syslimits.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/new.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/new
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/exception
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/hash_set
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/iostream
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/list
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkbullMarket.o: /usr/include/math.h /usr/include/gcc/darwin/default/g++/queue
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/slist
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/string
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/cstddef
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/cctype
vkbullMarket.o: /usr/include/ctype.h /usr/include/runetype.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/cstring
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/iterator
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/cassert
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkbullMarket.o: ../library/libstdc++/ducttape/sstream-2.95.3
vkbullMarket.o: /usr/include/time.h /usr/include/sys/time.h
vkbullMarket.o: /usr/include/gcc/darwin/default/g++/vector
vkbullSecurity.o: vkbullSecurity.h
test_vkbull.o: vkbullMarket.h ../vkmob/vkmobJect.h ../vkDef.h
test_vkbull.o: /usr/include/assert.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/cstdlib
test_vkbull.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
test_vkbull.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/fstream
test_vkbull.o: /usr/include/gcc/darwin/default/g++/fstream.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/iostream.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/streambuf.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/libio.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/_G_config.h
test_vkbull.o: /usr/include/sys/types.h /usr/include/machine/types.h
test_vkbull.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
test_vkbull.o: /usr/include/ppc/endian.h /usr/include/stddef.h
test_vkbull.o: /usr/include/stdarg.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/hash_map
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_config.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/type_traits.h
test_vkbull.o: /usr/include/string.h /usr/include/limits.h
test_vkbull.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
test_vkbull.o: /usr/include/sys/syslimits.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/new.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/new
test_vkbull.o: /usr/include/gcc/darwin/default/g++/exception
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_function.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/hash_set
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/iostream
test_vkbull.o: /usr/include/gcc/darwin/default/g++/list
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_list.h
test_vkbull.o: /usr/include/math.h /usr/include/gcc/darwin/default/g++/queue
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/slist
test_vkbull.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/string
test_vkbull.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/cstddef
test_vkbull.o: /usr/include/gcc/darwin/default/g++/std/straits.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/cctype
test_vkbull.o: /usr/include/ctype.h /usr/include/runetype.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/cstring
test_vkbull.o: /usr/include/gcc/darwin/default/g++/alloc.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/iterator
test_vkbull.o: /usr/include/gcc/darwin/default/g++/cassert
test_vkbull.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
test_vkbull.o: ../library/libstdc++/ducttape/sstream-2.95.3
test_vkbull.o: /usr/include/time.h /usr/include/sys/time.h
test_vkbull.o: /usr/include/gcc/darwin/default/g++/vector
