include ../vk.mk
srcs = \
	vkcgiApp.C \
	vkcgiMIMEType.C
module: \
	vkcgiApp.o \
	vkcgiMIMEType.o
moduleClean:
	rm -f test_vkcgi
moduleDepend:
moduleDependencies:
	cd ../vkapp && $(MAKE)
	cd ../vkhtml && $(MAKE)
# DO NOT DELETE

vkcgiApp.o: vkcgiApp.h vkcgiMIMEType.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/string
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/cstddef /usr/include/stddef.h
vkcgiApp.o: /usr/include/machine/ansi.h /usr/include/ppc/ansi.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/cctype /usr/include/ctype.h
vkcgiApp.o: /usr/include/runetype.h /usr/include/sys/cdefs.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/cstring /usr/include/string.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkcgiApp.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkcgiApp.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkcgiApp.o: /usr/include/ppc/endian.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/libio.h /usr/include/stdarg.h
vkcgiApp.o: /usr/include/stdlib.h /usr/include/assert.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/iterator
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/cassert
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkcgiApp.o: ../vkapp/vkappApp.h ../vkmob/vkmobFuncEqString.h
vkcgiApp.o: ../vkmob/vkmobJect.h ../vkDef.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/fstream
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/hash_map
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkcgiApp.o: /usr/include/limits.h /usr/include/machine/limits.h
vkcgiApp.o: /usr/include/ppc/limits.h /usr/include/sys/syslimits.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/new.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/new
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/exception
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/hash_set
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/iostream
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/list
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkcgiApp.o: /usr/include/math.h /usr/include/gcc/darwin/default/g++/queue
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/slist
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkcgiApp.o: ../library/libstdc++/ducttape/sstream-2.95.3 /usr/include/time.h
vkcgiApp.o: /usr/include/sys/time.h
vkcgiApp.o: /usr/include/gcc/darwin/default/g++/vector
vkcgiApp.o: ../vkmob/vkmobFuncHashString.h ../vkmob/vkmobJect.h
vkcgiApp.o: ../vkhtml/vkhtml.h ../vkhtml/vkhtmlA.h ../vkhtml/vkhtmlML.h
vkcgiApp.o: ../vkhtml/vkhtmlABBR.h ../vkhtml/vkhtmlACRONYM.h
vkcgiApp.o: ../vkhtml/vkhtmlADDRESS.h ../vkhtml/vkhtmlAREA.h
vkcgiApp.o: ../vkhtml/vkhtmlB.h ../vkhtml/vkhtmlBASE.h ../vkhtml/vkhtmlBDO.h
vkcgiApp.o: ../vkhtml/vkhtmlBIG.h ../vkhtml/vkhtmlBLOCKQUOTE.h
vkcgiApp.o: ../vkhtml/vkhtmlBODY.h ../vkhtml/vkhtmlBR.h
vkcgiApp.o: ../vkhtml/vkhtmlBUTTON.h ../vkhtml/vkhtmlCAPTION.h
vkcgiApp.o: ../vkhtml/vkhtmlCITE.h ../vkhtml/vkhtmlCODE.h
vkcgiApp.o: ../vkhtml/vkhtmlCOL.h ../vkhtml/vkhtmlCOLGROUP.h
vkcgiApp.o: ../vkhtml/vkhtmlDD.h ../vkhtml/vkhtmlDEL.h ../vkhtml/vkhtmlDFN.h
vkcgiApp.o: ../vkhtml/vkhtmlDIV.h ../vkhtml/vkhtmlDL.h ../vkhtml/vkhtmlDT.h
vkcgiApp.o: ../vkhtml/vkhtmlEM.h ../vkhtml/vkhtmlFIELDSET.h
vkcgiApp.o: ../vkhtml/vkhtmlFORM.h ../vkhtml/vkhtmlFRAME.h
vkcgiApp.o: ../vkhtml/vkhtmlFRAMESET.h ../vkhtml/vkhtmlH1.h
vkcgiApp.o: ../vkhtml/vkhtmlH2.h ../vkhtml/vkhtmlH3.h ../vkhtml/vkhtmlH4.h
vkcgiApp.o: ../vkhtml/vkhtmlH5.h ../vkhtml/vkhtmlH6.h ../vkhtml/vkhtmlHEAD.h
vkcgiApp.o: ../vkhtml/vkhtmlHR.h ../vkhtml/vkhtmlHTML.h ../vkhtml/vkhtmlI.h
vkcgiApp.o: ../vkhtml/vkhtmlIFRAME.h ../vkhtml/vkhtmlIMG.h
vkcgiApp.o: ../vkhtml/vkhtmlINPUT.h ../vkhtml/vkhtmlINS.h
vkcgiApp.o: ../vkhtml/vkhtmlKBD.h ../vkhtml/vkhtmlLABEL.h
vkcgiApp.o: ../vkhtml/vkhtmlLEGEND.h ../vkhtml/vkhtmlLI.h
vkcgiApp.o: ../vkhtml/vkhtmlLINK.h ../vkhtml/vkhtmlMAP.h
vkcgiApp.o: ../vkhtml/vkhtmlMETA.h ../vkhtml/vkhtmlNOFRAMES.h
vkcgiApp.o: ../vkhtml/vkhtmlNOSCRIPT.h ../vkhtml/vkhtmlOBJECT.h
vkcgiApp.o: ../vkhtml/vkhtmlOL.h ../vkhtml/vkhtmlOPTGROUP.h
vkcgiApp.o: ../vkhtml/vkhtmlOPTION.h ../vkhtml/vkhtmlP.h
vkcgiApp.o: ../vkhtml/vkhtmlPARAM.h ../vkhtml/vkhtmlPRE.h ../vkhtml/vkhtmlQ.h
vkcgiApp.o: ../vkhtml/vkhtmlSAMP.h ../vkhtml/vkhtmlSCRIPT.h
vkcgiApp.o: ../vkhtml/vkhtmlSELECT.h ../vkhtml/vkhtmlSMALL.h
vkcgiApp.o: ../vkhtml/vkhtmlSPAN.h ../vkhtml/vkhtmlSTRONG.h
vkcgiApp.o: ../vkhtml/vkhtmlSTYLE.h ../vkhtml/vkhtmlSUB.h
vkcgiApp.o: ../vkhtml/vkhtmlSUP.h ../vkhtml/vkhtmlTABLE.h
vkcgiApp.o: ../vkhtml/vkhtmlTBODY.h ../vkhtml/vkhtmlTD.h
vkcgiApp.o: ../vkhtml/vkhtmlTEXTAREA.h ../vkhtml/vkhtmlTFOOT.h
vkcgiApp.o: ../vkhtml/vkhtmlTH.h ../vkhtml/vkhtmlTHEAD.h
vkcgiApp.o: ../vkhtml/vkhtmlTITLE.h ../vkhtml/vkhtmlTR.h ../vkhtml/vkhtmlTT.h
vkcgiApp.o: ../vkhtml/vkhtmlText.h ../vkhtml/vkhtmlUL.h ../vkhtml/vkhtmlVAR.h
vkcgiMIMEType.o: vkcgiMIMEType.h /usr/include/gcc/darwin/default/g++/string
vkcgiMIMEType.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkcgiMIMEType.o: /usr/include/gcc/darwin/default/g++/cstddef
vkcgiMIMEType.o: /usr/include/stddef.h /usr/include/machine/ansi.h
vkcgiMIMEType.o: /usr/include/ppc/ansi.h
vkcgiMIMEType.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkcgiMIMEType.o: /usr/include/gcc/darwin/default/g++/cctype
vkcgiMIMEType.o: /usr/include/ctype.h /usr/include/runetype.h
vkcgiMIMEType.o: /usr/include/sys/cdefs.h
vkcgiMIMEType.o: /usr/include/gcc/darwin/default/g++/cstring
vkcgiMIMEType.o: /usr/include/string.h
vkcgiMIMEType.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkcgiMIMEType.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkcgiMIMEType.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkcgiMIMEType.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkcgiMIMEType.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkcgiMIMEType.o: /usr/include/ppc/endian.h
vkcgiMIMEType.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkcgiMIMEType.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkcgiMIMEType.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkcgiMIMEType.o: /usr/include/gcc/darwin/default/g++/libio.h
vkcgiMIMEType.o: /usr/include/stdarg.h /usr/include/stdlib.h
vkcgiMIMEType.o: /usr/include/assert.h
vkcgiMIMEType.o: /usr/include/gcc/darwin/default/g++/iterator
vkcgiMIMEType.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkcgiMIMEType.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkcgiMIMEType.o: /usr/include/gcc/darwin/default/g++/cassert
vkcgiMIMEType.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
