include ../vk.mk
srcs = \
	vkjackHJ.C \
	vkjackMimic.C \
	vkjackNeuron.C \
	redblue.C \
	test_vkjack.C \
	test_vkjackMimic.C
module: \
	vkjackHJ.o \
	vkjackMimic.o \
	vkjackNeuron.o \
	redblue \
	test_vkjack \
	test_vkjackMimic
moduleClean:
	rm -f redblue
	rm -f test_vkjack
	rm -f test_vkjackMimic
	rm -f red.hj
	rm -f blue.hj
moduleDepend:
moduleDependencies:
	cd ../vkmob && $(MAKE)
redblue: $(srcs)
	g++  $(CPPFLAGS)  -o redblue redblue.C *.o ../vkmob/*.o
test_vkjack: $(srcs)
	g++  $(CPPFLAGS)  -o test_vkjack test_vkjack.C *.o ../vkmob/*.o
test_vkjackMimic: $(srcs)
	g++  $(CPPFLAGS)  -o test_vkjackMimic test_vkjackMimic.C *.o ../vkmob/*.o
# DO NOT DELETE

vkjackHJ.o: vkjackHJ.h ../vkmob/vkmobDigestable.h ../vkmob/vkmobJect.h
vkjackHJ.o: ../vkDef.h /usr/include/assert.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/cstdlib /usr/include/stdlib.h
vkjackHJ.o: /usr/include/machine/ansi.h /usr/include/ppc/ansi.h
vkjackHJ.o: /usr/include/sys/cdefs.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/fstream
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/libio.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkjackHJ.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkjackHJ.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkjackHJ.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkjackHJ.o: /usr/include/stdarg.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/hash_map
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkjackHJ.o: /usr/include/string.h /usr/include/limits.h
vkjackHJ.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vkjackHJ.o: /usr/include/sys/syslimits.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/new.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/new
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/exception
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/hash_set
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/iostream
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/list
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkjackHJ.o: /usr/include/math.h /usr/include/gcc/darwin/default/g++/queue
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/slist
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/string
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/cstddef
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/cctype /usr/include/ctype.h
vkjackHJ.o: /usr/include/runetype.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/cstring
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/iterator
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/cassert
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkjackHJ.o: ../library/libstdc++/ducttape/sstream-2.95.3 /usr/include/time.h
vkjackHJ.o: /usr/include/sys/time.h
vkjackHJ.o: /usr/include/gcc/darwin/default/g++/vector ../vkmob/vkmobRandom.h
vkjackHJ.o: vkjackNeuron.h ../vkmath/vkmathBoolBinOps.h
vkjackMimic.o: vkjackMimic.h ../vkmob/vkmobLogable.h ../vkmob/vkmobLog.h
vkjackMimic.o: ../vkmob/vkmobJect.h ../vkDef.h /usr/include/assert.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/cstdlib
vkjackMimic.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
vkjackMimic.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/fstream
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/fstream.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/iostream.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/streambuf.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/libio.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/_G_config.h
vkjackMimic.o: /usr/include/sys/types.h /usr/include/machine/types.h
vkjackMimic.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
vkjackMimic.o: /usr/include/ppc/endian.h /usr/include/stddef.h
vkjackMimic.o: /usr/include/stdarg.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/hash_map
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_config.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/type_traits.h
vkjackMimic.o: /usr/include/string.h /usr/include/limits.h
vkjackMimic.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
vkjackMimic.o: /usr/include/sys/syslimits.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/new.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/new
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/exception
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_function.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/hash_set
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/iostream
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/list
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_list.h
vkjackMimic.o: /usr/include/math.h /usr/include/gcc/darwin/default/g++/queue
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/slist
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/string
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/cstddef
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/std/straits.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/cctype
vkjackMimic.o: /usr/include/ctype.h /usr/include/runetype.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/cstring
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/alloc.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/iterator
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/cassert
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
vkjackMimic.o: ../library/libstdc++/ducttape/sstream-2.95.3
vkjackMimic.o: /usr/include/time.h /usr/include/sys/time.h
vkjackMimic.o: /usr/include/gcc/darwin/default/g++/vector
vkjackMimic.o: ../vkmob/vkmobLogConsts.h ../vkmob/vkmobTimeFormat.h
vkjackMimic.o: vkjackHJ.h ../vkmob/vkmobDigestable.h ../vkmob/vkmobRandom.h
vkjackMimic.o: vkjackNeuron.h ../vkmath/vkmathBoolBinOps.h
vkjackNeuron.o: vkjackNeuron.h
redblue.o: vkjackHJ.h ../vkmob/vkmobDigestable.h ../vkmob/vkmobJect.h
redblue.o: ../vkDef.h /usr/include/assert.h
redblue.o: /usr/include/gcc/darwin/default/g++/cstdlib /usr/include/stdlib.h
redblue.o: /usr/include/machine/ansi.h /usr/include/ppc/ansi.h
redblue.o: /usr/include/sys/cdefs.h
redblue.o: /usr/include/gcc/darwin/default/g++/fstream
redblue.o: /usr/include/gcc/darwin/default/g++/fstream.h
redblue.o: /usr/include/gcc/darwin/default/g++/iostream.h
redblue.o: /usr/include/gcc/darwin/default/g++/streambuf.h
redblue.o: /usr/include/gcc/darwin/default/g++/libio.h
redblue.o: /usr/include/gcc/darwin/default/g++/_G_config.h
redblue.o: /usr/include/sys/types.h /usr/include/machine/types.h
redblue.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
redblue.o: /usr/include/ppc/endian.h /usr/include/stddef.h
redblue.o: /usr/include/stdarg.h /usr/include/gcc/darwin/default/g++/hash_map
redblue.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
redblue.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
redblue.o: /usr/include/gcc/darwin/default/g++/stl_config.h
redblue.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
redblue.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
redblue.o: /usr/include/gcc/darwin/default/g++/type_traits.h
redblue.o: /usr/include/string.h /usr/include/limits.h
redblue.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
redblue.o: /usr/include/sys/syslimits.h
redblue.o: /usr/include/gcc/darwin/default/g++/new.h
redblue.o: /usr/include/gcc/darwin/default/g++/new
redblue.o: /usr/include/gcc/darwin/default/g++/exception
redblue.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
redblue.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
redblue.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
redblue.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
redblue.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
redblue.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
redblue.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
redblue.o: /usr/include/gcc/darwin/default/g++/stl_function.h
redblue.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
redblue.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
redblue.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
redblue.o: /usr/include/gcc/darwin/default/g++/hash_set
redblue.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
redblue.o: /usr/include/gcc/darwin/default/g++/iostream
redblue.o: /usr/include/gcc/darwin/default/g++/list
redblue.o: /usr/include/gcc/darwin/default/g++/stl_list.h /usr/include/math.h
redblue.o: /usr/include/gcc/darwin/default/g++/queue
redblue.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
redblue.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
redblue.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
redblue.o: /usr/include/gcc/darwin/default/g++/slist
redblue.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
redblue.o: /usr/include/gcc/darwin/default/g++/string
redblue.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
redblue.o: /usr/include/gcc/darwin/default/g++/cstddef
redblue.o: /usr/include/gcc/darwin/default/g++/std/straits.h
redblue.o: /usr/include/gcc/darwin/default/g++/cctype /usr/include/ctype.h
redblue.o: /usr/include/runetype.h
redblue.o: /usr/include/gcc/darwin/default/g++/cstring
redblue.o: /usr/include/gcc/darwin/default/g++/alloc.h
redblue.o: /usr/include/gcc/darwin/default/g++/iterator
redblue.o: /usr/include/gcc/darwin/default/g++/cassert
redblue.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
redblue.o: ../library/libstdc++/ducttape/sstream-2.95.3 /usr/include/time.h
redblue.o: /usr/include/sys/time.h /usr/include/gcc/darwin/default/g++/vector
redblue.o: ../vkmob/vkmobRandom.h vkjackNeuron.h ../vkmath/vkmathBoolBinOps.h
test_vkjack.o: vkjackHJ.h ../vkmob/vkmobDigestable.h ../vkmob/vkmobJect.h
test_vkjack.o: ../vkDef.h /usr/include/assert.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/cstdlib
test_vkjack.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
test_vkjack.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/fstream
test_vkjack.o: /usr/include/gcc/darwin/default/g++/fstream.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/iostream.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/streambuf.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/libio.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/_G_config.h
test_vkjack.o: /usr/include/sys/types.h /usr/include/machine/types.h
test_vkjack.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
test_vkjack.o: /usr/include/ppc/endian.h /usr/include/stddef.h
test_vkjack.o: /usr/include/stdarg.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/hash_map
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_config.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/type_traits.h
test_vkjack.o: /usr/include/string.h /usr/include/limits.h
test_vkjack.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
test_vkjack.o: /usr/include/sys/syslimits.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/new.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/new
test_vkjack.o: /usr/include/gcc/darwin/default/g++/exception
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_function.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/hash_set
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/iostream
test_vkjack.o: /usr/include/gcc/darwin/default/g++/list
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_list.h
test_vkjack.o: /usr/include/math.h /usr/include/gcc/darwin/default/g++/queue
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/slist
test_vkjack.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/string
test_vkjack.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/cstddef
test_vkjack.o: /usr/include/gcc/darwin/default/g++/std/straits.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/cctype
test_vkjack.o: /usr/include/ctype.h /usr/include/runetype.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/cstring
test_vkjack.o: /usr/include/gcc/darwin/default/g++/alloc.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/iterator
test_vkjack.o: /usr/include/gcc/darwin/default/g++/cassert
test_vkjack.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
test_vkjack.o: ../library/libstdc++/ducttape/sstream-2.95.3
test_vkjack.o: /usr/include/time.h /usr/include/sys/time.h
test_vkjack.o: /usr/include/gcc/darwin/default/g++/vector
test_vkjack.o: ../vkmob/vkmobRandom.h vkjackNeuron.h
test_vkjack.o: ../vkmath/vkmathBoolBinOps.h
test_vkjackMimic.o: vkjackMimic.h ../vkmob/vkmobLogable.h ../vkmob/vkmobLog.h
test_vkjackMimic.o: ../vkmob/vkmobJect.h ../vkDef.h /usr/include/assert.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/cstdlib
test_vkjackMimic.o: /usr/include/stdlib.h /usr/include/machine/ansi.h
test_vkjackMimic.o: /usr/include/ppc/ansi.h /usr/include/sys/cdefs.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/fstream
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/fstream.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/iostream.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/streambuf.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/libio.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/_G_config.h
test_vkjackMimic.o: /usr/include/sys/types.h /usr/include/machine/types.h
test_vkjackMimic.o: /usr/include/ppc/types.h /usr/include/machine/endian.h
test_vkjackMimic.o: /usr/include/ppc/endian.h /usr/include/stddef.h
test_vkjackMimic.o: /usr/include/stdarg.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/hash_map
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_hashtable.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_algobase.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_config.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_relops.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_pair.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/type_traits.h
test_vkjackMimic.o: /usr/include/string.h /usr/include/limits.h
test_vkjackMimic.o: /usr/include/machine/limits.h /usr/include/ppc/limits.h
test_vkjackMimic.o: /usr/include/sys/syslimits.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/new.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/new
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/exception
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_iterator.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_alloc.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_construct.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_tempbuf.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_algo.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_heap.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_uninitialized.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_function.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_vector.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_hash_fun.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_hash_map.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/hash_set
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_hash_set.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/iostream
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/list
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_list.h
test_vkjackMimic.o: /usr/include/math.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/queue
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_bvector.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_deque.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_queue.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/slist
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/stl_slist.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/string
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/std/bastring.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/cstddef
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/std/straits.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/cctype
test_vkjackMimic.o: /usr/include/ctype.h /usr/include/runetype.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/cstring
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/alloc.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/iterator
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/cassert
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/std/bastring.cc
test_vkjackMimic.o: ../library/libstdc++/ducttape/sstream-2.95.3
test_vkjackMimic.o: /usr/include/time.h /usr/include/sys/time.h
test_vkjackMimic.o: /usr/include/gcc/darwin/default/g++/vector
test_vkjackMimic.o: ../vkmob/vkmobLogConsts.h ../vkmob/vkmobTimeFormat.h
test_vkjackMimic.o: vkjackHJ.h ../vkmob/vkmobDigestable.h
test_vkjackMimic.o: ../vkmob/vkmobRandom.h vkjackNeuron.h
test_vkjackMimic.o: ../vkmath/vkmathBoolBinOps.h
test_vkjackMimic.o: ../vkmob/vkmobLogDeviceCout.h ../vkmob/vkmobLogDevice.h
